name: CheesecakeMinigameLobby
main: io.github.itachi1706.CheesecakeMinigameLobby.Main
version: 1.1
description: An internal plugin for minigame server
author: itachi1706
commands:
  cheesecakeminigamelobby version:
    description: Main Plugin Command
    usage: /cheesecakeminigamelobby version
    permission: cheesecakeminigamelobby.default
    permission-message: You do not have permission to do this command
permissions:
  cheesecakeminigamelobby.default:
    description: Default command
    default: true
  cheesecakeminigamelobby.exempt:
    description: Prevents being hidden
    default: op