name: FTBOpJoinAnnounce
main: io.github.itachi1706.FTBOpJoinAnnounce.Main
version: 1.3
description: An internal plugin for announcing ops and devs join
author: itachi1706
commands:
  opjoin:
    description: Main Plugin Command
    usage: /opjoin
    permission: opjoinannounce.default
    permission-message: You do not have permission to do this command
  joinannounce:
    description: Sub Plugin Command
    usage: /joinannounce [dev/status/op]
    permission: opjoinannounce.default
    permission-message: You do not have permission to do this command
  mojang:
    description: Mojang Servers
    usage: /mojang status
    permission: opjoinannounce.default
    permission-message: You do not have permission to do this command
permissions:
  opjoinannounce.edit:
    description: Allows you to edit OP Perms
    default: op
  opjoinannounce.default:
    description: Default command
    default: true