name: MunKeiSux
main: io.github.itachi1706.munkeisux.MunKei
version: 0.0.1
description: Le Troll Plugin
author: itachi1706
commands:
  munkei:
    description: munkei troll command
    usage: /munkei <player>
    permission: mk.default
    permission-message: You do not have permission to do this command.
permissions:
  mk.default:
    description: Default command
    default: true